const jobs=[{id:"OT-1042",car:"Honda CR-V 2018",task:"Diagnóstico ruido tren delantero",status:"Diagnóstico",team:"José + Carlos"},{id:"OT-1045",car:"Toyota Corolla 2020",task:"Frenos delanteros",status:"Pendiente",team:"Carlos"},{id:"OT-1047",car:"Ford F-150 2019",task:"A/C no enfría",status:"En reparación",team:"José"}];
let logged=sessionStorage.emp==="1";let tab="Inicio";
function login(){const p=document.querySelector("#pass").value;if(p.length<4)return alert("Contraseña inválida.");sessionStorage.emp="1";logged=true;render()}
function logout(){sessionStorage.clear();location.reload()}
function setTab(t){tab=t;render()}
function card(j){return '<div class="job"><div class="row"><div><b>'+j.id+'</b><div>'+j.car+'</div></div><span class="pill">'+j.status+'</span></div><p>'+j.task+'</p><div class="muted">Equipo: '+j.team+'</div><button class="btn" style="margin-top:12px" onclick="openJob(\''+j.id+'\')">Abrir orden</button></div>'}
function openJob(id){const j=jobs.find(x=>x.id===id);document.querySelector("#view").innerHTML='<button class="btn" onclick="setTab(\'Órdenes\')">← Volver</button><div class="card" style="margin-top:14px"><h2>'+j.id+' · '+j.car+'</h2><p>'+j.task+'</p><label>Estado</label><select><option>'+j.status+'</option><option>En camino</option><option>Diagnóstico</option><option>Esperando piezas</option><option>En reparación</option><option>Completado</option></select><label>Diagnóstico</label><textarea rows="5" placeholder="Hallazgos, pruebas realizadas, recomendaciones..."></textarea><label>Piezas utilizadas</label><input placeholder="Ej. pads delanteros, 1 filtro..."><div class="check"><input type="checkbox"> <span>Trabajo verificado</span></div><button class="btn" onclick="alert(\'Cambios guardados localmente en este MVP\')">Guardar actualización</button></div>'}
function body(){if(tab==="Inicio")return '<div class="grid"><div class="metric">Mis órdenes<strong>3</strong></div><div class="metric">Pendientes<strong>1</strong></div></div><h3>Próximos trabajos</h3><div class="list">'+jobs.slice(0,2).map(card).join("")+'</div>';if(tab==="Órdenes")return '<h2>Órdenes de trabajo</h2><div class="list">'+jobs.map(card).join("")+'</div>';if(tab==="Diagnóstico")return '<div class="card"><h2>Diagnóstico rápido</h2><input placeholder="Orden de trabajo"><textarea rows="6" placeholder="Síntomas, pruebas, códigos, causa probable..."></textarea><button class="btn" onclick="alert(\'Diagnóstico guardado en MVP\')">Guardar diagnóstico</button></div>';if(tab==="Equipo")return '<div class="card"><h2>Trabajo en equipo</h2><div class="list"><div class="job"><b>José</b><div class="muted">2 órdenes activas</div></div><div class="job"><b>Carlos</b><div class="muted">2 órdenes activas</div></div></div></div>';return '<div class="card"><h2>Evidencias</h2><p class="muted">Módulo preparado para fotos, videos y firma del cliente al conectar almacenamiento real.</p><input type="file" multiple accept="image/*"><button class="btn" onclick="alert(\'La carga real se habilitará con backend\')">Subir evidencia</button></div>'}
function render(){const a=document.querySelector("#app");if(!logged){a.innerHTML='<div class="login"><div class="card"><div class="brand"><div class="mark">TE</div><span>Portal de Empleados</span></div><p class="muted">Acceso operativo al taller</p><input id="pass" type="password" placeholder="Contraseña"><button class="btn" onclick="login()">Entrar</button><p class="muted" style="font-size:12px">MVP: acceso local temporal. Producción requiere autenticación segura y roles.</p></div></div>';return}const tabs=["Inicio","Órdenes","Diagnóstico","Equipo","Evidencias"];a.innerHTML='<div class="shell"><div class="top"><div class="brand"><div class="mark">TE</div><div>Portal Empleados<div class="muted" style="font-size:13px">Órdenes · Diagnóstico · Equipo</div></div></div><button class="btn" onclick="logout()">Salir</button></div><div class="tabs">'+tabs.map(t=>'<button class="'+(t===tab?"active":"")+'" onclick="setTab(\''+t+'\')">'+t+'</button>').join("")+'</div><div id="view">'+body()+'</div></div>'}
render();if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");